
[functions.process-subscription]
enabled = true
verify_jwt = false
import_map = "./functions/process-subscription/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/process-subscription/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/process-subscription/*.html" ]

[functions.pay-subscription]
enabled = true
verify_jwt = false
import_map = "./functions/pay-subscription/deno.json"
entrypoint = "./functions/pay-subscription/index.ts"

[functions.create-checkout]
enabled = true
verify_jwt = false
import_map = "./functions/create-checkout/deno.json"
entrypoint = "./functions/create-checkout/index.ts"

[functions.complete-onboarding]
enabled = true
verify_jwt = false
import_map = "./functions/complete-onboarding/deno.json"
entrypoint = "./functions/complete-onboarding/index.ts"

[functions.onboarding]
enabled = true
verify_jwt = false
import_map = "./functions/onboarding/deno.json"
entrypoint = "./functions/onboarding/index.ts"

[functions.send-invite]
enabled = true
verify_jwt = false
import_map = "./functions/send-invite/deno.json"
entrypoint = "./functions/send-invite/index.ts"

[functions.webhook-asaas]
enabled = true
verify_jwt = false
import_map = "./functions/webhook-asaas/deno.json"
entrypoint = "./functions/webhook-asaas/index.ts"

[functions.correct-essay]
enabled = true
verify_jwt = false
import_map = "./functions/correct-essay/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/correct-essay/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/correct-essay/*.html" ]

[functions.generate-theme]
enabled = true
verify_jwt = false
import_map = "./functions/generate-theme/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate-theme/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate-theme/*.html" ]

[functions.start-trial]
enabled = true
verify_jwt = false
import_map = "./functions/start-trial/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/start-trial/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/start-trial/*.html" ]

[functions.submit-lead]
enabled = true
verify_jwt = false
import_map = "./functions/submit-lead/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/submit-lead/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/submit-lead/*.html" ]

[functions.register-trial-student]
enabled = true
verify_jwt = false
import_map = "./functions/register-trial-student/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/register-trial-student/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/register-trial-student/*.html" ]

[functions.convert-trial-school]
enabled = true
verify_jwt = false
import_map = "./functions/convert-trial-school/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/convert-trial-school/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/convert-trial-school/*.html" ]

[functions.activate-trial]
enabled = true
verify_jwt = false
import_map = "./functions/activate-trial/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/activate-trial/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/activate-trial/*.html" ]
