// api/webhook.ts
import { createClient } from '@supabase/supabase-js';
import { applyCors } from './_cors';

export default async function handler(req: any, res: any) {
    if (applyCors(req, res)) return;
    if (req.method !== 'POST') {
        return res.status(405).json({ message: 'Method Not Allowed' });
    }

    try {
        const { userId, schoolName, email, cpfCnpj, name, phone, planPrice, frequency, planName } = req.body;

        if (!userId || !email) {
            return res.status(400).json({ message: 'userId and email are required' });
        }

        const amount = planPrice ? parseFloat(planPrice) : 29.90;

        // Configuração do Asaas
        const asaasToken = process.env.ASAAS_API_KEY || process.env.VITE_ASAAS_API_KEY || '';
        // Usa Sandbox se a chave tiver 'hmlg' ou 'sandbox', senão usa Produção.
        const asaasUrl = asaasToken.includes('hmlg') || asaasToken.includes('sandbox')
            ? 'https://sandbox.asaas.com/api/v3'
            : 'https://api.asaas.com/v3';

        // 1. Criar Link de Pagamento no Asaas
        const billingCycle = frequency === 12 ? 'YEARLY' : (frequency === 6 ? 'SEMIANNUALLY' : 'MONTHLY');
        const planName = frequency === 12 ? 'Anual' : (frequency === 6 ? 'Semestral' : 'Mensal');

        const payRes = await fetch(`${asaasUrl}/paymentLinks`, {
            method: 'POST',
            headers: {
                'access_token': asaasToken,
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
            body: JSON.stringify({
                billingType: 'UNDEFINED',
                chargeType: 'RECURRENT',
                name: `Assinatura Littera Pro ${planName}`,
                description: `Acesso Corporativo - Littera`,
                value: amount,
                endDate: null,
                cycle: billingCycle,
                dueDateLimitDays: 1,
                maxInstallmentCount: 1
            })
        });

        const paymentLink = await payRes.json();

        if (paymentLink.errors) {
            console.error('Asaas Link Error:', paymentLink.errors);
            return res.status(400).json({ message: 'Erro ao gerar pagamento no Asaas', error: paymentLink.errors[0]?.description });
        }

        // 2. Criar a Escola com pending_payment no Supabase
        const supabaseUrl = process.env.VITE_SUPABASE_URL || '';
        const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.VITE_SUPABASE_KEY || '';

        if (supabaseUrl && supabaseKey && userId) {
            const supabase = createClient(supabaseUrl, supabaseKey);
            const cleanSlug = schoolName.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');

            const { data: schoolData, error: schoolError } = await supabase.from('schools').insert({
                name: schoolName,
                slug: cleanSlug || `escola-${Date.now()}`,
                subscription_status: 'pending_payment',
                payment_link_id: paymentLink.id,
                asaas_customer_id: null // customer is only generated by Asaas after they pay using the link
            }).select().single();

            if (schoolData && !schoolError) {
                // Cria o profile
                await supabase.from('profiles').upsert({
                    id: userId,
                    school_id: schoolData.id,
                    role: 'school_admin',
                    full_name: name,
                    email: email,
                    status: 'active'
                });
            } else {
                console.error('Supabase update error:', schoolError);
            }
        }

        // 3. Retornar a URL de checkout
        return res.status(200).json({
            checkoutUrl: paymentLink.url,
            linkId: paymentLink.id
        });

    } catch (error: any) {
        console.error('Error creating Asaas payment:', error);
        return res.status(500).json({ message: 'Internal Server Error', error: error.message });
    }
}